### ISSUE TITLE
Add Price comparing section

### ISSUE THREAD

**Issue by NadiaFrShLm** [appwex/izzy-health#27]
As per [Figma](https://www.figma.com/file/5oiHJDRRXElpM37qRm1j18/Izzyhealth-landing-page-(Community)?node-id=0%3A1&t=6ZOVwjFGh7vRBtsr-0)

# Preview

<div align="center">

![Screenshot 2023-01-23 at 10 29 20](https://user-images.githubusercontent.com/84836971/214006129-98471e33-430f-4a62-a74d-52ae095426e3.png)

</div>

## Notes

**Comment by saroshfarhan** [comment]
Closing this issue.
