### ISSUE TITLE
Add Footer Component

### ISSUE THREAD

**Issue by mrxshinji** [appwex/izzy-health#3]
As per [Figma](https://www.figma.com/file/5oiHJDRRXElpM37qRm1j18/Izzyhealth-landing-page-(Community)?node-id=1%3A298&t=6ZOVwjFGh7vRBtsr-4)

# Preview 

<div align="center">

![Image](https://user-images.githubusercontent.com/95459307/207234189-6eb2ec98-b9a4-4c4a-b94d-931aa4ffc357.png)

</div>

**Comment by mrxshinji** [comment]
@saroshfarhan Do not need to have background for this footer, it will fit into doctor section later

**Comment by saroshfarhan** [comment]
ok @mrxshinji

**Comment by saroshfarhan** [comment]
@mrxshinji the design doesn't have a mobile design, should I keep everything in a column for small screen devices?

**Comment by saroshfarhan** [comment]
@mrxshinji @aftabrehan have raised PR #24, request you to please review and merge this. Thanks!
